services:
  app:
    build: .
    container_name: python-server
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - 8080:8080
      - 5678:5678
    volumes:
      - .:/code