name: update-prod
on:
  # update the branch prod every 3 days
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Prod Merge 🛎
        run: gh pr create -B prod -H dev --title 'Merge dev into prod' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  